#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1
start_service() {
 procd_open_instance
 procd_set_param command /bin/sh -c 'while :; do if /usr/libexec/c2000max-bing; then sleep 900; else sleep 30; fi; done'
 procd_set_param respawn 3600 5 5
 procd_set_param stdout 0
 procd_set_param stderr 0
 procd_close_instance
}
